MAILSERVER_ADDRESS: 'smtp.gmail.com'
MAILSERVER_PORT: '587'
MAILSERVER_USERNAME: 'admin@polco.us'
MAILSERVER_PASSWORD: '282ma2a@'
MAILSERVER_DOMAIN: 'polco.us'
ADMIN_EMAIL_ADDRESS: 'admin@polco.us'
DEFAULT_URL: 'www.polco.us'
DEFAULT_MAIL_FROM: 'admin@polco.us'
DEVELOPMENT_MAIL_RECIPIENT: 'admin@theboohers.org'