defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: polco_development

test:
  <<: *defaults
  database: polco_test

# set these environment variables on your prod server
# TODO not sure if we need to set these . . .
production:
 uri: <%= ENV['MONGOHQ_URL'] %>
 # MONGOHQ_URL
#  database: polco_production
#  host: <%= ENV['MONGOID_HOST'] %>
#  port: <%= ENV['MONGOID_PORT'] %>
#  username: <%= ENV['MONGOID_USERNAME'] %>
#  password: <%= ENV['MONGOID_PASSWORD'] %>
#  database: <%= ENV['MONGOID_DATABASE'] %>