#OpenSSL::SSL::VERIFY_PEER: OpenSSL::SSL::VERIFY_NONE

OMNIAUTH_OPENID: true
OMNIAUTH_GOOGLE: true
OMNIAUTH_CAPATH: "/etc/ssl/certs"

GOOGLE_PLACE_API_KEY: 'not_used_for_v3'

OMNIAUTH_TWITTER_KEY: '66TbDqljky5GXX0XDJA'
OMNIAUTH_TWITTER_SECRET: 'e1hlyIzzTcmkr2X4bnOqblh0qEMmSyBWb9rRQI0riU'

OMNIAUTH_FACEBOOK_KEY: '180732375308137'
OMNIAUTH_FACEBOOK_SECRET: 'f345b26a8b32755b6f3f9873f73d931b'

OMNIAUTH_LINKED_IN_KEY: 'v9ynrph_sBg1B_V0MyCBZgCEXZffJn2f1vIs0jR8DvDjKwTSygeiC43myFqKMWeg'
OMNIAUTH_LINKED_IN_SECRET: 'x99YDTd0uSggdP4xgzSqFK0zr-o1EhE_X3YR1fIOBUILs6HpDTvIzrcyYV_zubQl'

#OMNIAUTH_BASECAMP_ID: 'YOUR_OMNIAUTH_BASECAMP_ID'
#OMNIAUTH_BASECAMP_SECRET: 'YOUR_OMNIAUTH_BASECAMP_SECRET'

OMNIAUTH_GITHUB_ID: '39d3fb4d2ba224982d1c'
OMNIAUTH_GITHUB_SECRET: '5e8e91c0f43f23af21c5c3b9123440e5354cf690'
